name: Deploy to Beget

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build project
        run: |
          cd frontend
          npm run build

      - name: Remove unwanted files before deployment
        run: |
          rm -rf frontend/node_modules
          rm -f frontend/.env
          rm -f frontend/package-lock.json

      - name: Sync files to Beget
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.BEGET_HOST }}
          username: ${{ secrets.BEGET_USERNAME }}
          password: ${{ secrets.BEGET_PASSWORD }}
          source: "frontend/"
          target: "/"

      - name: Clean up deleted files on Beget
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.BEGET_HOST }}
          username: ${{ secrets.BEGET_USERNAME }}
          password: ${{ secrets.BEGET_PASSWORD }}
          script: |
            rsync -av --delete frontend/ /
