name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: cd frontend && npm install

      - name: Build project
        run: cd frontend && npm run build

      - name: Deploy to Beget
        if: github.ref == 'refs/heads/main'
        env:
          BEGET_HOST: ${{ secrets.BEGET_HOST }}
          BEGET_USER: ${{ secrets.BEGET_USER }}
          BEGET_PASS: ${{ secrets.BEGET_PASS }}
        run: |
          apt-get update
          apt-get install -y lftp
          lftp -c "open -u $BEGET_USER,$BEGET_PASS $BEGET_HOST; mirror -R ./frontend/build public_html"
