name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: cd frontend && npm install

      - name: Build project
        run: cd frontend && npm run build

      - name: Deploy to Beget
        if: github.ref == 'refs/heads/main'
        env:
          BEGET_HOST: ${{ secrets.BEGET_HOST }}
          BEGET_USER: ${{ secrets.BEGET_USER }}
          BEGET_PASS: ${{ secrets.BEGET_PASS }}
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp
          echo "Starting deployment..."
          lftp -c "
          set ssl:verify-certificate no;
          open -u $BEGET_USER,$BEGET_PASS $BEGET_HOST;
          mirror -R --delete --parallel=10 --verbose --exclude-glob node_modules/ --exclude-glob package-lock.json --exclude-glob .env ./ / || exit 1
          "
          echo "Deployment completed."
